# Generated by Django 5.2.6 on 2025-09-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
